### ISSUE TITLE
Cannot install role with Ansible 6 / 2.13.6

### ISSUE THREAD

**Issue by janArb** [ontic/ansible-role-fonts#2]
I try to install, but only get an error message.

Here is what happens:

```
$ ansible-galaxy install ontic.fonts
Starting galaxy role install process
- downloading role 'fonts', owned by ontic
- downloading role from https://github.com/ontic/ansible-role-fonts/archive/v2.4.0.tar.gz
[WARNING]: - ontic.fonts was NOT installed successfully: this role does not appear to have a meta/Debian.yml file.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

Obviously there is no `meta/Debian.yml`, correct. But why is it even needed?

Maybe it's a local issue?

```
$ ansible-galaxy --version
ansible-galaxy [core 2.13.6]
  config file = .../ansible/test/ansible.cfg
  configured module search path = ['/home/.../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = .../ansible6/lib/python3.8/site-packages/ansible
  ansible collection location = /home/.../.ansible/collections:/usr/share/ansible/collections
  executable location = ...ansible6/bin/ansible-galaxy
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

**Comment by adamdyson** [comment]
Use `requirements.yml` when using Ansible Galaxy. Also using `-f` will force overwriting an existing role or collection.

```
ansible-galaxy install -f -r requirements.yml
```

**Comment by janArb** [comment]
Hey,
yeah I'm using a `requirements.yml` but tried to separate the issue. I tried again with the `-f` force flag and `requirements.yml` and realized the very same error occurs for a different dependency, too now. I created a new python virtual env and the issue is not reproducible there. So really a good argument for virtual env again. Can get damaged. Thanks for your feedback here.
